### ISSUE TITLE
Usable for video elements?

### ISSUE THREAD

**Issue by BHuys** [elevationsoftware/cordova-plugin-camera-stream#2]
Is it possible to use this stream as a srcObject for a video element?

**Comment by pirumpi** [comment]
This was a solution for an older version of iOS, now you can just use good old getUserMedia to access camera from javascript.

```js
navigator.mediaDevices.getUserMedia(constraints)
.then(function(stream) {
  /* use the stream */
})
.catch(function(err) {
  /* handle the error */
});```

**Comment by BHuys** [comment]
Thanks for your reply but for some reason getUserMedia is not supported in my app, I'll check my versions but as far as I now, these are the latest.

**Comment by pirumpi** [comment]
Ok, to make sure you version of iOS supports video access just go to this size https://www.auduno.com/clmtrackr/examples/clm_video.html and see if your iPad/iPhone will allow access to the video!
