### ISSUE TITLE
Plugin still running after quitting page, reloading page, or navigating to another page

### ISSUE THREAD

**Issue by hadi-el-hajj** [elevationsoftware/cordova-plugin-camera-stream#6]
Issue:  The camera is till being used and the stream is still being sent, even after quitting the page which uses the camera. 
Desired behavior:  The plugin should stop completely upon page quit, to avoid using resources used otherwise by the rest of the application. 

In summary, there must be a plugin function quit, which when called, closes the AVSession and stops streaming.

**Comment by pirumpi** [comment]
can you call pause before navigating from the page?

**Comment by hadi-el-hajj** [comment]
No, I tried to use the onunload event so I can call the pause function when the event is triggered, but it won't do.
Since I am using Angular, I also tried calling it from the ngOnDestroy, nothing either. 
Do you have some other possible solutions in mind ?

**Comment by pirumpi** [comment]
Are you able to get the pause function to work at all? The strategy of calling it on ngDestroy should be a good solution, but I wonder if the pause method is broken? I can try to create a sample app this weekend to test that functionality

**Comment by pirumpi** [comment]
Silly question, are you adding the OnDestroy interface to your component class? Without it, Angular won't run the ngOnDestroy

**Comment by hadi-el-hajj** [comment]
Yes, of course, with no positive result.
