### ISSUE TITLE
Swift version compatibility

### ISSUE THREAD

**Issue by dufrenb** [elevationsoftware/cordova-plugin-camera-stream#7]
Hi ! We are using your plugin to build a cordova app with angular that runs on IOS at least 11.

On our development environment we have XCode v12.5.1 with support for Swift v5. But it seems that you plugin uses swift v3. Is it possible for you to migrate in a newer version of swift ?

**Comment by pirumpi** [comment]
Are you having compatibility issues? the code should work fine on v5

**Comment by dufrenb** [comment]
The plugin is functionnal but I have an error on `cordova build`: `Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.` 

The error seems to be related to the version of `cordova-plugin-swift-support` which is a dependency of your plugin. The solution would be to upgrade it. See the changelog: https://github.com/akofman/cordova-plugin-add-swift-support/blob/master/CHANGELOG.md.

Could you update it ?

**Comment by pirumpi** [comment]
If you needed right away, I can take and review a PR, otherwise, I'll need time to make the changes and test the upgrade

**Comment by dufrenb** [comment]
For now, I have too much on my plate and do not have the time to build a PR. If it is possible it would be great if you take the time to do it. Otherwise, maybe I will have time to do around september!
